### ISSUE TITLE
E-mail contact not working

### ISSUE THREAD

**Issue by brunowego** [SunblockFinance/sunblock#16]
HI @arkalon76 , I'm opening this issue just to inform you that your email [hello@sunblock.finance](mailto:hello@sunblock.finance), at this moment, are not working. Regards.

**Comment by arkalon76** [comment]
Thanks for the report @brunowego. DNS settings are fixed and should be good to go now. 👍

**Comment by brunowego** [comment]
Great! Have a nice day!
